# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: a

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v6

    - name: Install dep
      run: |
        choco install mingw
        choco install windows-sdk-10.1
      
    - name: Build
      run: g++ RedSun.cpp -o redsun
      
    - name: Artifact
      run: |
        mkdir artifacts
        cp redsun artifacts/
